kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 10040
    targetPort: 10041
    protocol: TCP
  selector:
    app: nginx